const ADD_TODO = "ADD_TODO"
const FETCH_TODOS = "FETCH_TODOS"
const DELETE_TODO = "DELETE_TODO"
const SET_TODOS = "SET_TODOS"
const SET_FILTER_TO_DONE = "SET_FILTER_TO_DONE"
const SET_FILTER_TO_UNDONE = "SET_FILTER_TO_UNDONE"
const SET_FILTER_TO_ALL = "SET_FILTER_TO_ALL"

export {
    ADD_TODO, 
    FETCH_TODOS, 
    DELETE_TODO, 
    SET_TODOS, 
    SET_FILTER_TO_DONE, 
    SET_FILTER_TO_UNDONE, 
    SET_FILTER_TO_ALL
}